version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: nlmongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: nlmongo_db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nlmongo_server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nlmongo_client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  mongo_data:
